In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import statistics
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')



df1=pd.read_csv('/content/drive/MyDrive/Capstone-Thesis/Datasets/kiva_small_loans/loan_themes_by_region.csv')
print(df1.shape) #shows num of row and column
df1.head(10)

(15736, 21)

,Partner ID,Field Partner Name,sector,Loan Theme ID,Loan Theme Type,country,forkiva,region,geocode_old,ISO,...,amount,LocationName,geocode,names,geo,lat,lon,mpi_region,mpi_geo,rural_pct
0,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Banteay Meanchey,"(13.75, 103.0)",KHM,...,450,"Banteay Meanchey, Cambodia","[(13.6672596, 102.8975098)]",Banteay Meanchey Province; Cambodia,"(13.6672596, 102.8975098)",13.667260,102.897510,"Banteay Mean Chey, Cambodia","(13.6672596, 102.8975098)",90.0
1,9,KREDIT Microfinance Institution,General Financial Inclusion,a10500000068jPe,Vulnerable Populations,Cambodia,No,Battambang Province,NaN,KHM,...,20275,"Battambang Province, Cambodia","[(13.0286971, 102.989615)]",Battambang Province; Cambodia,"(13.0286971, 102.989615)",13.028697,102.989615,"Banteay Mean Chey, Cambodia","(13.6672596, 102.8975098)",90.0
2,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Battambang Province,NaN,KHM,...,9150,"Battambang Province, Cambodia","[(13.0286971, 102.989615)]",Battambang Province; Cambodia,"(13.0286971, 102.989615)",13.028697,102.989615,"Banteay Mean Chey, Cambodia","(13.6672596, 102.8975098)",90.0
3,9,KREDIT Microfinance Institution,General Financial Inclusion,a10500000068jPe,Vulnerable Populations,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,604950,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
4,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000002X1Uu,Sanitation,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,275,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
5,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,62225,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
6,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000007VvXr,Solar Home Systems,Cambodia,No,Kampong Cham Province,"(12.0, 105.5)",KHM,...,1300,"Kampong Cham Province, Cambodia","[(12.0982918, 105.3131185)]",Kampong Cham Province; Cambodia,"(12.0982918, 105.3131185)",12.098292,105.313119,"Kampong Cham, Cambodia","(11.9924294, 105.4645408)",90.0
7,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000weyk,General,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,237175,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0
8,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000007VvXr,Solar Home Systems,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,3050,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0
9,9,KREDIT Microfinance Institution,General Financial Inclusion,a1050000000slfi,Higher Education,Cambodia,No,Kampong Chhnang Province,"(12.0, 104.5)",KHM,...,31425,"Kampong Chhnang Province, Cambodia","[(12.1392352, 104.5655273)]",Kampong Chhnang Province; Cambodia,"(12.1392352, 104.5655273)",12.139235,104.565527,"Kampong Chhnang, Cambodia","(12.1392352, 104.5655273)",90.0

In [ ]:
# remove columns (Loan Theme ID, Loan Theme Type, forkiva, geocode_old, ISO, number, amount, geocode, geo, lat, lon, mpi_geo)

cols_to_drop = ['Loan Theme ID', 'Loan Theme Type', 'forkiva', 'geocode_old', 'ISO', 'number', 'amount', 'geocode', 'geo', 'lat', 'lon', 'mpi_geo']
df1 = df1.drop(columns=cols_to_drop, errors='ignore')
print(df1.shape)
df1.head(10)

(15736, 9)

,Partner ID,Field Partner Name,sector,country,region,LocationName,names,mpi_region,rural_pct
0,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Banteay Meanchey,"Banteay Meanchey, Cambodia",Banteay Meanchey Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0
1,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Battambang Province,"Battambang Province, Cambodia",Battambang Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0
2,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Battambang Province,"Battambang Province, Cambodia",Battambang Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0
3,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",90.0
4,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",90.0
5,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",90.0
6,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",90.0
7,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Chhnang Province,"Kampong Chhnang Province, Cambodia",Kampong Chhnang Province; Cambodia,"Kampong Chhnang, Cambodia",90.0
8,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Chhnang Province,"Kampong Chhnang Province, Cambodia",Kampong Chhnang Province; Cambodia,"Kampong Chhnang, Cambodia",90.0
9,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Chhnang Province,"Kampong Chhnang Province, Cambodia",Kampong Chhnang Province; Cambodia,"Kampong Chhnang, Cambodia",90.0

In [ ]:
# duplicate rows

duplicate_rows_df = df1[df1.duplicated()]
print("Number of duplicate rows: ", duplicate_rows_df.shape)

Number of duplicate rows:  (5641, 9)

In [ ]:
# drop the duplicate rows

df1 = df1.drop_duplicates()
print("Shape of dataframe after removing duplicates: ", df1.shape)
df1.head(10)

Shape of dataframe after removing duplicates:  (10095, 9)

,Partner ID,Field Partner Name,sector,country,region,LocationName,names,mpi_region,rural_pct
0,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Banteay Meanchey,"Banteay Meanchey, Cambodia",Banteay Meanchey Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0
1,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Battambang Province,"Battambang Province, Cambodia",Battambang Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0
3,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",90.0
7,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Chhnang Province,"Kampong Chhnang Province, Cambodia",Kampong Chhnang Province; Cambodia,"Kampong Chhnang, Cambodia",90.0
12,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Speu Province,"Kampong Speu Province, Cambodia",Kampong Speu Province; Cambodia,"Phnom Penh, Cambodia",90.0
15,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampot Province,"Kampot Province, Cambodia",Kampot Province; Cambodia,"Kampot & Kep, Cambodia",90.0
16,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kandal Province,"Kandal Province, Cambodia",Kandal; Cambodia,"Kandal, Cambodia",90.0
19,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kratie Province,"Kratie Province, Cambodia",KratiÍ© Province; Cambodia,"Kratie, Cambodia",90.0
21,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Phnom Penh,"Phnom Penh, Cambodia",Phnom Penh; Phnom Penh; Cambodia,"Phnom Penh, Cambodia",90.0
22,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Prey Veng Province,"Prey Veng Province, Cambodia",Prey Veng Province; Cambodia,"Prey Veng, Cambodia",90.0

In [ ]:
df2=pd.read_csv('/content/drive/MyDrive/Capstone-Thesis/Datasets/kiva_small_loans/kiva_mpi_region_locations.csv')
print(df2.shape) #shows num of row and column
df2.head(3)

(1008, 9)

,LocationName,ISO,country,region,world_region,MPI,geo,lat,lon
0,"Badakhshan, Afghanistan",AFG,Afghanistan,Badakhshan,South Asia,0.387,"(36.7347725, 70.81199529999999)",36.734772,70.811995
1,"Badghis, Afghanistan",AFG,Afghanistan,Badghis,South Asia,0.466,"(35.1671339, 63.7695384)",35.167134,63.769538
2,"Baghlan, Afghanistan",AFG,Afghanistan,Baghlan,South Asia,0.300,"(35.8042947, 69.2877535)",35.804295,69.287753

In [ ]:
print(df1.isnull().sum())

Partner ID               0
Field Partner Name       0
sector                   0
country                  0
region                   0
LocationName             0
names                 1758
mpi_region               7
rural_pct              936
dtype: int64

In [ ]:
# Find null values in df2
print(df2.isnull().sum())

LocationName     24
ISO               0
country           0
region           24
world_region      0
MPI              24
geo               0
lat             116
lon             116
dtype: int64

In [ ]:
# drop the row where LocationName, region  ,MPI   is null

df2 = df2.dropna(subset=['LocationName', 'region', 'MPI'])
print(df2.shape)
df2.head(3)

(984, 9)

,LocationName,ISO,country,region,world_region,MPI,geo,lat,lon
0,"Badakhshan, Afghanistan",AFG,Afghanistan,Badakhshan,South Asia,0.387,"(36.7347725, 70.81199529999999)",36.734772,70.811995
1,"Badghis, Afghanistan",AFG,Afghanistan,Badghis,South Asia,0.466,"(35.1671339, 63.7695384)",35.167134,63.769538
2,"Baghlan, Afghanistan",AFG,Afghanistan,Baghlan,South Asia,0.300,"(35.8042947, 69.2877535)",35.804295,69.287753

In [ ]:
df1 = df1.dropna(subset=['names', 'mpi_region'])
print(df1.shape)
df1.head(3)

(8330, 9)

,Partner ID,Field Partner Name,sector,country,region,LocationName,names,mpi_region,rural_pct
0,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Banteay Meanchey,"Banteay Meanchey, Cambodia",Banteay Meanchey Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0
1,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Battambang Province,"Battambang Province, Cambodia",Battambang Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0
3,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",90.0

In [ ]:

# Merge df1 and df2 based on mpi_region and LocationName, keeping only the MPI column from df2
merged_df = pd.merge(df1, df2[['LocationName', 'MPI']], left_on='mpi_region', right_on='LocationName', how='left')

print(merged_df.shape)
merged_df.head(10)

(8330, 11)

,Partner ID,Field Partner Name,sector,country,region,LocationName_x,names,mpi_region,rural_pct,LocationName_y,MPI
0,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Banteay Meanchey,"Banteay Meanchey, Cambodia",Banteay Meanchey Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0,"Banteay Mean Chey, Cambodia",0.097
1,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Battambang Province,"Battambang Province, Cambodia",Battambang Province; Cambodia,"Banteay Mean Chey, Cambodia",90.0,"Banteay Mean Chey, Cambodia",0.097
2,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",90.0,"Kampong Cham, Cambodia",0.160
3,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Chhnang Province,"Kampong Chhnang Province, Cambodia",Kampong Chhnang Province; Cambodia,"Kampong Chhnang, Cambodia",90.0,"Kampong Chhnang, Cambodia",0.193
4,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampong Speu Province,"Kampong Speu Province, Cambodia",Kampong Speu Province; Cambodia,"Phnom Penh, Cambodia",90.0,"Phnom Penh, Cambodia",0.026
5,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kampot Province,"Kampot Province, Cambodia",Kampot Province; Cambodia,"Kampot & Kep, Cambodia",90.0,"Kampot & Kep, Cambodia",0.155
6,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kandal Province,"Kandal Province, Cambodia",Kandal; Cambodia,"Kandal, Cambodia",90.0,"Kandal, Cambodia",0.121
7,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Kratie Province,"Kratie Province, Cambodia",KratiÍ© Province; Cambodia,"Kratie, Cambodia",90.0,"Kratie, Cambodia",0.274
8,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Phnom Penh,"Phnom Penh, Cambodia",Phnom Penh; Phnom Penh; Cambodia,"Phnom Penh, Cambodia",90.0,"Phnom Penh, Cambodia",0.026
9,9,KREDIT Microfinance Institution,General Financial Inclusion,Cambodia,Prey Veng Province,"Prey Veng Province, Cambodia",Prey Veng Province; Cambodia,"Prey Veng, Cambodia",90.0,"Prey Veng, Cambodia",0.120

In [ ]:
# Drop specified columns
cols_to_drop = ['Partner ID', 'Field Partner Name', 'sector',  'LocationName_y', 'rural_pct']
merged_df = merged_df.drop(columns=cols_to_drop, errors='ignore')

print(merged_df.shape)


# Find null values
null_values = merged_df.isnull().sum()
null_values

(8330, 6)

country              0
region               0
LocationName_x       0
names                0
mpi_region           0
MPI               2190
dtype: int64

In [ ]:
merged_df.head(10)

,country,region,LocationName_x,names,mpi_region,MPI
0,Cambodia,Banteay Meanchey,"Banteay Meanchey, Cambodia",Banteay Meanchey Province; Cambodia,"Banteay Mean Chey, Cambodia",0.097
1,Cambodia,Battambang Province,"Battambang Province, Cambodia",Battambang Province; Cambodia,"Banteay Mean Chey, Cambodia",0.097
2,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",0.160
3,Cambodia,Kampong Chhnang Province,"Kampong Chhnang Province, Cambodia",Kampong Chhnang Province; Cambodia,"Kampong Chhnang, Cambodia",0.193
4,Cambodia,Kampong Speu Province,"Kampong Speu Province, Cambodia",Kampong Speu Province; Cambodia,"Phnom Penh, Cambodia",0.026
5,Cambodia,Kampot Province,"Kampot Province, Cambodia",Kampot Province; Cambodia,"Kampot & Kep, Cambodia",0.155
6,Cambodia,Kandal Province,"Kandal Province, Cambodia",Kandal; Cambodia,"Kandal, Cambodia",0.121
7,Cambodia,Kratie Province,"Kratie Province, Cambodia",KratiÍ© Province; Cambodia,"Kratie, Cambodia",0.274
8,Cambodia,Phnom Penh,"Phnom Penh, Cambodia",Phnom Penh; Phnom Penh; Cambodia,"Phnom Penh, Cambodia",0.026
9,Cambodia,Prey Veng Province,"Prey Veng Province, Cambodia",Prey Veng Province; Cambodia,"Prey Veng, Cambodia",0.120

In [ ]:

# Iterate through rows where 'MPI' is null
for index, row in merged_df[merged_df['MPI'].isnull()].iterrows():
    # Check if any word from 'names' column exists in 'region' column of df2
    name_words = row['names'].split()  # Split 'names' into words
    for word in name_words:
        if any(word in region for region in df2['region']):
            # If a match is found, fill the 'MPI' with a suitable value (e.g., from df2)
            # You might want to refine this logic based on how you want to fill the missing value
            # Here, I'm taking the first matching region's MPI.
            matching_region = df2[df2['region'].str.contains(word, case=False, na=False)].iloc[0]
            merged_df.loc[index, 'MPI'] = matching_region['MPI']
            break  # Exit the inner loop once a match is found

In [ ]:
# Find null values in the merged dataframe
null_values = merged_df.isnull().sum()
null_values

country              0
region               0
LocationName_x       0
names                0
mpi_region           0
MPI               1567
dtype: int64

In [ ]:
# prompt: if the MPI is null check it the 'region' column == df2's 'region'. if matches then fillup the empty cell then check for null values

# Iterate through rows where 'MPI' is null
for index, row in merged_df[merged_df['MPI'].isnull()].iterrows():
    # Check if the 'region' in df2 matches the 'mpi_region' in the current row
    matching_regions = df2[df2['region'] == row['region']]
    if not matching_regions.empty:
        merged_df.loc[index, 'MPI'] = matching_regions['MPI'].iloc[0]

# Find null values in the merged dataframe
null_values = merged_df.isnull().sum()
null_values

country              0
region               0
LocationName_x       0
names                0
mpi_region           0
MPI               1563
dtype: int64

In [ ]:
# if the MPI is null check it the merged_df's 'LocationName' column == df2's 'LocationName'. if matches then fillup the empty cell then check for null values

# Iterate through rows where 'MPI' is null
for index, row in merged_df[merged_df['MPI'].isnull()].iterrows():
    # Check if 'LocationName' in merged_df matches 'LocationName' in df2
    matching_locations = df2[df2['LocationName'] == row['LocationName_x']]
    if not matching_locations.empty:
        merged_df.loc[index, 'MPI'] = matching_locations['MPI'].iloc[0]

# Find null values in the merged dataframe
null_values = merged_df.isnull().sum()
null_values

country              0
region               0
LocationName_x       0
names                0
mpi_region           0
MPI               1563
dtype: int64

In [ ]:
print(merged_df.shape)
merged_df.head(50)

(8330, 6)

,country,region,LocationName_x,names,mpi_region,MPI
0,Cambodia,Banteay Meanchey,"Banteay Meanchey, Cambodia",Banteay Meanchey Province; Cambodia,"Banteay Mean Chey, Cambodia",0.097
1,Cambodia,Battambang Province,"Battambang Province, Cambodia",Battambang Province; Cambodia,"Banteay Mean Chey, Cambodia",0.097
2,Cambodia,Kampong Cham Province,"Kampong Cham Province, Cambodia",Kampong Cham Province; Cambodia,"Kampong Cham, Cambodia",0.160
3,Cambodia,Kampong Chhnang Province,"Kampong Chhnang Province, Cambodia",Kampong Chhnang Province; Cambodia,"Kampong Chhnang, Cambodia",0.193
4,Cambodia,Kampong Speu Province,"Kampong Speu Province, Cambodia",Kampong Speu Province; Cambodia,"Phnom Penh, Cambodia",0.026
5,Cambodia,Kampot Province,"Kampot Province, Cambodia",Kampot Province; Cambodia,"Kampot & Kep, Cambodia",0.155
6,Cambodia,Kandal Province,"Kandal Province, Cambodia",Kandal; Cambodia,"Kandal, Cambodia",0.121
7,Cambodia,Kratie Province,"Kratie Province, Cambodia",KratiÍ© Province; Cambodia,"Kratie, Cambodia",0.274
8,Cambodia,Phnom Penh,"Phnom Penh, Cambodia",Phnom Penh; Phnom Penh; Cambodia,"Phnom Penh, Cambodia",0.026
9,Cambodia,Prey Veng Province,"Prey Veng Province, Cambodia",Prey Veng Province; Cambodia,"Prey Veng, Cambodia",0.120
10,Cambodia,Pursat Province,"Pursat Province, Cambodia",Pursat Province; Cambodia,"Pursat, Cambodia",0.221
11,Cambodia,Siem Reap Province,"Siem Reap Province, Cambodia",Siem Reap Province; Cambodia,"Siem Reap, Cambodia",0.204
12,Cambodia,Steung Traeng Province,"Steung Traeng Province, Cambodia",Steung Treng Province; Cambodia,"Kratie, Cambodia",0.274
13,Cambodia,Svay Reang Province,"Svay Reang Province, Cambodia",Svay Rieng Province; Cambodia,"Svay Rieng, Cambodia",0.100
14,Cambodia,Takeo province,"Takeo province, Cambodia",TakÍ©o Province; Cambodia,"Takeo, Cambodia",0.106
15,Cambodia,Tbong Khmum Province,"Tbong Khmum Province, Cambodia",Tbong Khmum Province; Cambodia,"Kampong Cham, Cambodia",0.160
16,Samoa,Aai o FIti,"Aai o FIti, Samoa",Aai o Fiti; Apia; Upolu; Samoa,WSM,0.384
17,Samoa,Afega,"Afega, Samoa",Afega; Upolu; Samoa,WSM,NaN
18,Samoa,Afiamalu,"Afiamalu, Samoa",Afiamalu; Tuamasaga; Samoa,WSM,NaN
19,Samoa,Alafua,"Alafua, Samoa",Alafua; Apia; Tuamasaga; Samoa,WSM,NaN
20,Samoa,Alamagoto,"Alamagoto, Samoa",Alamagoto; Apia; Upolu; Samoa,WSM,NaN
21,Samoa,Alaoa,"Alaoa, Samoa",Alaoa Road; Apia; Tuamasaga; Samoa,WSM,NaN
22,Samoa,Aleisa,"Aleisa, Samoa",Camp Samoa Community; Apia; Samoa,WSM,NaN
23,Samoa,"Aopo, Savaii","Aopo, Savaii, Samoa",A'opo; Savai'i; Samoa,WSM,NaN
24,Samoa,Apia,"Apia, Samoa",Apia; Upolu; Samoa,WSM,NaN
25,Samoa,Apolima,"Apolima, Samoa",Apolima; Samoa,WSM,NaN
26,Samoa,"Asaga, Savaii","Asaga, Savaii, Samoa",Asaga; Savai'i; Samoa,WSM,NaN
27,Samoa,Asau,"Asau, Samoa",Asau; Savai'i; Samoa,WSM,NaN
28,Samoa,Auala,"Auala, Samoa",Auala; Savai'i; Samoa,WSM,NaN
29,Samoa,Aufaga,"Aufaga, Samoa",Aufaga; Atua; Samoa,WSM,NaN
30,Samoa,"Avao, Savaii","Avao, Savaii, Samoa",Savai'i; Samoa,WSM,NaN
31,Samoa,Avele,"Avele, Samoa",Avele; Apia; Upolu; Samoa,WSM,NaN
32,Samoa,Elise Fou,"Elise Fou, Samoa",Elisefou; Vaitele; Upolu; Samoa,WSM,NaN
33,Samoa,Eva,"Eva, Samoa",Samoa Way; South Cirby; Roseville; Placer Coun...,WSM,0.005
34,Samoa,FAUSAGA,"FAUSAGA, Samoa",Fausaga; Upolu; Samoa,WSM,NaN
35,Samoa,Faatoia,"Faatoia, Samoa",Faatoia; Apia; Upolu; Samoa,WSM,NaN
36,Samoa,"Faga, Savaii Island","Faga, Savaii Island, Samoa",Faga; Savai'i; Samoa,WSM,NaN
37,Samoa,Fagafau,"Fagafau, Samoa",Fagafau; Savai'i; Samoa,WSM,NaN
38,Samoa,Fagalii Uta,"Fagalii Uta, Samoa",Fagali'i; Apia; Upolu; Samoa,WSM,NaN
39,Samoa,Fagaloa Taelefaga,"Fagaloa Taelefaga, Samoa",Taelefaga; Upolu; Samoa,WSM,NaN
40,Samoa,"Fagamalo, Savaii","Fagamalo, Savaii, Samoa",Fagamalo; Gaga'emauga; Savai'i; Samoa,WSM,NaN
41,Samoa,Fagasa,"Fagasa, Samoa",Fagasa; Ituau; Eastern; American Samoa,WSM,NaN
42,Samoa,"Faiaai, Savaii","Faiaai, Savaii, Samoa",Faiaai Beach; Samoa,WSM,NaN
43,Samoa,Falealili,"Falealili, Samoa",Falealili Street; Apia; Tuamasaga; Samoa,WSM,NaN
44,Samoa,Falealupo Savaii,"Falealupo Savaii, Samoa",Falealupo; Savai'i; Samoa,WSM,NaN
45,Samoa,"Falealupo, Savaii","Falealupo, Savaii, Samoa",Falealupo; Savai'i; Samoa,WSM,NaN
46,Samoa,Faleapuna,"Faleapuna, Samoa",Faleapuna; Atua; Samoa,WSM,NaN
47,Samoa,Faleaseela,"Faleaseela, Samoa",Falease'ela; A'ana; Samoa,WSM,NaN
48,Samoa,Faleasiu,"Faleasiu, Samoa",Faleasiu; A'ana; Samoa,WSM,NaN
49,Samoa,Falefa,"Falefa, Samoa",Falefa; Atua; Samoa,WSM,NaN

In [ ]:
# Drop rows where 'MPI' is null
merged_df = merged_df.dropna(subset=['MPI'])

# Check for null values again
null_values = merged_df.isnull().sum()
null_values

country           0
region            0
LocationName_x    0
names             0
mpi_region        0
MPI               0
dtype: int64

In [ ]:
print(merged_df.shape)

(6767, 6)

In [ ]:
# download the csv

from google.colab import files
merged_df.to_csv('merged_data.csv', encoding = 'utf-8-sig')
files.download('merged_data.csv')